<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Aprendizado de Máquina
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Teoria;</li>
  <li>Atributos categóricos;</li>
  <li>Atributos numéricos;</li>
  <li>Dados faltantes.</li>
</ol>

---

# **Exercícios**

## 1\. Pinguins

Neste exercício, vamos utilizar uma base de dados com informações sobre penguins. A idéia é preparar a base de dados para prever a espécie do penguin (variável resposta) baseado em suas características físicas e geográficas (variáveis preditivas).

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
data = sns.load_dataset('penguins')
df = pd.DataFrame(data)

In [3]:
print(df)

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0
1    Adelie  Torgersen            39.5           17.4              186.0
2    Adelie  Torgersen            40.3           18.0              195.0
3    Adelie  Torgersen             NaN            NaN                NaN
4    Adelie  Torgersen            36.7           19.3              193.0
..      ...        ...             ...            ...                ...
339  Gentoo     Biscoe             NaN            NaN                NaN
340  Gentoo     Biscoe            46.8           14.3              215.0
341  Gentoo     Biscoe            50.4           15.7              222.0
342  Gentoo     Biscoe            45.2           14.8              212.0
343  Gentoo     Biscoe            49.9           16.1              213.0

     body_mass_g     sex
0         3750.0    Male
1         3800.0  Female
2         3250.0  Female
3            NaN     NaN
4         3450.0  Female
..           ...     ...
339          NaN     NaN
340       4850.0  Female
341       5750.0    Male
342       5200.0  Female
343       5400.0    Male

[344 rows x 7 columns]

In [4]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

### **1.1. Valores nulos**

A base de dados possui valores faltantes, utilize os conceitos da aula para trata-los.

In [5]:
# resposta da questão 1.1
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [6]:
display(df[df.isnull().any(axis=1)])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
246,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN
286,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN
324,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN
336,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

In [7]:
df['bill_length_mm'] = df['bill_length_mm'].fillna(df['bill_length_mm'].mean())
df['bill_depth_mm'] = df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())
df['flipper_length_mm'] = df['flipper_length_mm'].fillna(df['flipper_length_mm'].mean())
df['body_mass_g'] = df['body_mass_g'].fillna(df['body_mass_g'].mean())
df = df.drop('sex', axis=1)

In [8]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
dtype: int64

In [9]:
display(df[df.isnull().any(axis=1)])

Empty DataFrame
Columns: [species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g]
Index: []

### **1.2. Variáveis numéricas**

Identifique as variáveis numéricas e crie uma nova coluna **padronizando** seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_std*".

> **Nota**: Você não deve tratar a variável resposta.

In [10]:
# resposta da questão 1.2
df['bill_length_mm_std'] = df['bill_length_mm'].apply(lambda valor: (valor - df['bill_length_mm'].mean()) / df['bill_length_mm'].std() )
df['bill_depth_mm_std'] = df['bill_depth_mm'].apply(lambda valor: (valor - df['bill_depth_mm'].mean()) / df['bill_depth_mm'].std() )
df['flipper_length_mm_std'] = df['flipper_length_mm'].apply(lambda valor: (valor - df['flipper_length_mm'].mean()) / df['flipper_length_mm'].std() )
df['body_mass_g_std'] = df['body_mass_g'].apply(lambda valor: (valor - df['body_mass_g'].mean()) / df['body_mass_g'].std() )

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std,body_mass_g_std
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,-8.857909e-01,7.865967e-01,-1.420419,-0.564966
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,-8.123107e-01,1.263722e-01,-1.063802,-0.502436
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,-6.653503e-01,4.310912e-01,-0.421892,-1.190269
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,-1.305271e-15,1.804299e-15,0.000000,0.000000
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,-1.326672e+00,1.091316e+00,-0.564539,-0.940148

### **1.3. Variáveis categóricas**

Identifique as variáveis categóricas nominais e ordinais, crie uma nova coluna aplicando a técnica correta de conversão a seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_nom*" ou "*_ord*".

> **Nota**: Você não deve tratar a variável resposta.

In [11]:
# resposta da questão 1.3
df['island'].drop_duplicates()

0     Torgersen
20       Biscoe
30        Dream
Name: island, dtype: object

In [14]:

df['island_nom_Torgersen'] = df['island'].apply(lambda valor: 1 if valor == 'Torgersen' else 0)
df['island_nom_Biscoe'] = df['island'].apply(lambda valor: 1 if valor == 'Biscoe' else 0)
df['island_nom_Dream'] = df['island'].apply(lambda valor: 1 if valor == 'Dream' else 0)

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std,body_mass_g_std,island_nom_Torgersen,island_nom_Biscoe,island_nom_Dream
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,-8.857909e-01,7.865967e-01,-1.420419,-0.564966,1,0,0
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,-8.123107e-01,1.263722e-01,-1.063802,-0.502436,1,0,0
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,-6.653503e-01,4.310912e-01,-0.421892,-1.190269,1,0,0
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,-1.305271e-15,1.804299e-15,0.000000,0.000000,1,0,0
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,-1.326672e+00,1.091316e+00,-0.564539,-0.940148,1,0,0

### **1.4. Limpeza**

Descarte as colunas originais e mantenha apenas a variável resposta e as variáveis preditivas com o sufixo *_std*", *_nom*" e "*_ord*".

In [ ]:
# resposta da questão 1.4
df.columns

In [15]:
df = df[['species', 'bill_length_mm_std',
             'bill_depth_mm_std', 'flipper_length_mm_std',
             'body_mass_g_std','island_nom_Torgersen',
             'island_nom_Biscoe', 'island_nom_Dream'
]]


df.head()

,species,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std,body_mass_g_std,island_nom_Torgersen,island_nom_Biscoe,island_nom_Dream
0,Adelie,-8.857909e-01,7.865967e-01,-1.420419,-0.564966,1,0,0
1,Adelie,-8.123107e-01,1.263722e-01,-1.063802,-0.502436,1,0,0
2,Adelie,-6.653503e-01,4.310912e-01,-0.421892,-1.190269,1,0,0
3,Adelie,-1.305271e-15,1.804299e-15,0.000000,0.000000,1,0,0
4,Adelie,-1.326672e+00,1.091316e+00,-0.564539,-0.940148,1,0,0

---